name: ✨ 功能建议
description: 建议一个新功能或改进已有的功能, 期待你的 Idea.
labels: ["enhancement"]
body:
- type: textarea
  attributes:
    label: 问题描述
    description: 请添加一个清晰且简洁的描述，说明你正在解决的问题。
  validations:
    required: true
- type: textarea
  attributes:
    label: 建议解决方案
    description: |
      描述你希望实现的解决方案或功能。
      暂不考虑 重打包 和 Hook 功能
  validations:
    required: false
- type: textarea
  attributes:
    label: 替代方案
    description: 描述你考虑过的任何替代解决方案或功能。
  validations:
    required: false
- type: textarea
  attributes:
    label: 额外信息
    description: 如果你的问题需要进一步解释，请在这里添加更多信息。
  validations:
    required: false